s@\(os map texture \).*base-badlands.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/026d0a76.zip@
s@\(os map texture \).*base-birchforest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/20a08b5d.zip@
s@\(os map texture \).*base-coldswamphills.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/9f10bf94.zip@
s@\(os map texture \).*base-crimson.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/dd816e7e.zip@
s@\(os map texture \).*base-dark.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/18cbc782.zip@
s@\(os map texture \).*base-darkforest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/0f7e1cd2.zip@
s@\(os map texture \).*base-desert.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/1bb53a4b.zip@
s@\(os map texture \).*base-forest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/1f9bd59e.zip@
s@\(os map texture \).*base-inventory.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/3556f517.zip@
s@\(os map texture \).*base-jungle.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/60583c77.zip@
s@\(os map texture \).*base-jungleedge.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/0de22873.zip@
s@\(os map texture \).*base-mountains.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/70da9aee.zip@
s@\(os map texture \).*base-multi.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/12f9b475.zip@
s@\(os map texture \).*base-mushroom.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/3b03423e.zip@
s@\(os map texture \).*base-plains.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/ed31bdb6.zip@
s@\(os map texture \).*base-river.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/4eb20887.zip@
s@\(os map texture \).*base-snowy.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/0cf74cf8.zip@
s@\(os map texture \).*base-snowybeach.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/5c583261.zip@
s@\(os map texture \).*base-spruceforest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/7fdab2fc.zip@
s@\(os map texture \).*base-spruceforestgiant.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/565ec483.zip@
s@\(os map texture \).*base-swamp.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/6a6e1f3b.zip@
s@\(os map texture \).*base-warped.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/3e4a4496.zip@
s@\(os map texture \).*base.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/12f9b475.zip@
s@\(os map texture \).*mc-13.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/040e2429.zip@
s@\(os map texture \).*mc-16.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/e069185c.zip@
s@\(os map texture \).*mix-badlands.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/db895aca.zip@
s@\(os map texture \).*mix-birchforest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/3b89fabd.zip@
s@\(os map texture \).*mix-coldswamphills.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/f5bc0a13.zip@
s@\(os map texture \).*mix-crimson.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/de8e7e58.zip@
s@\(os map texture \).*mix-dark.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/631ca376.zip@
s@\(os map texture \).*mix-darkforest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/8b51559c.zip@
s@\(os map texture \).*mix-desert.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/49185e45.zip@
s@\(os map texture \).*mix-forest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/39ffde20.zip@
s@\(os map texture \).*mix-inventory.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/76e489e8.zip@
s@\(os map texture \).*mix-jungle.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/9339b17f.zip@
s@\(os map texture \).*mix-jungleedge.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/57d54b68.zip@
s@\(os map texture \).*mix-mountains.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/824d39a6.zip@
s@\(os map texture \).*mix-multi.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/3593f82f.zip@
s@\(os map texture \).*mix-mushroom.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/9212e2b1.zip@
s@\(os map texture \).*mix-plains.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/ea574367.zip@
s@\(os map texture \).*mix-river.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/f304d668.zip@
s@\(os map texture \).*mix-snowy.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/a0da6ba4.zip@
s@\(os map texture \).*mix-snowybeach.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/f405536c.zip@
s@\(os map texture \).*mix-spruceforest.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/03360e8a.zip@
s@\(os map texture \).*mix-spruceforestgiant.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/3a52836f.zip@
s@\(os map texture \).*mix-swamp.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/e0791bad.zip@
s@\(os map texture \).*mix-warped.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/0e41765e.zip@
s@\(os map texture \).*mix.zip@\1https://raw.githubusercontent.com/rdebath/mc/zip/dfb057f7.zip@
